;; Added by Package.el.  This must come before configurations of
;; installed packages.  Don't delete this line.  If you don't want it,
;; just comment it out by adding a semicolon to the start of the line.
;; You may delete these explanatory comments.
(require 'package)
(let* ((no-ssl (and (memq system-type '(windows-nt ms-dos))
                    (not (gnutls-available-p))))
       (proto (if no-ssl "http" "https")))
  (when no-ssl
    (warn "\
Your version of Emacs does not support SSL connections,
which is unsafe because it allows man-in-the-middle attacks.
There are two things you can do about this warning:
1. Install an Emacs version that does support SSL and be safe.
2. Remove this warning from your init file so you won't see it again."))
  (add-to-list 'package-archives (cons "melpa" (concat proto "://melpa.org/packages/")) t))
(package-initialize)

;; Global binds
(global-unset-key (kbd "C-x C-p"))
(global-unset-key (kbd "C-x C-n"))
(global-set-key (kbd "C-]") 'other-frame)
(global-set-key (kbd "C-o") 'other-window)
(global-set-key (kbd "M-o") 'myprevious-window)
(global-set-key (kbd "C-x {") 'shrink-window)
(global-set-key (kbd "C-x }") 'enlarge-window)
(global-set-key (kbd "C-x [") 'shrink-window-horizontally)
(global-set-key (kbd "C-x ]") 'enlarge-window-horizontally)
(global-set-key (kbd "C-x k") 'kill-this-buffer)
;;(global-set-key (kbd "C-x C-b") 'ibuffer)
(global-set-key (kbd "M-r") 'replace-regexp)
;;(global-set-key (kbd "C-s") 'isearch-forward-regexp)
;;(global-set-key (kbd "C-r") 'isearch-backward-regexp)
;;(global-set-key (kbd "C-M-s") 'rgrep)
(global-set-key (kbd "C-x /") 'comment-line)
(global-set-key (kbd "C-c M-l") 'org-store-link)

;; Appearance
(set-face-background 'vertical-border  'unspecified)
(global-prettify-symbols-mode +1)
(global-visual-line-mode 1); Proper line wrapping
(tool-bar-mode -1)
(menu-bar-mode -1)
(add-hook 'prog-mode-hook 'line-number-mode)
(setq font-use-system-font t)
(setq frame-background-mode 'dark)

;; Parens
(use-package emacs
  :custom
  (show-paren-mode 1)
  (setq show-paren-style 'parenthesis))
(setq blink-matching-paren t)

;; Emacs Server config
(setq server-socket-dir "~/.emacs.d/servers/")

;; Custom modes
(add-to-list 'load-path "~/.emacs.d/lisp")
(cond ((locate-library "llvm-mode") (require 'llvm-mode)))
(cond ((locate-library "tablegen-mode") (require 'tablegen-mode)))
(cond ((locate-library "mlir-mode") (require 'mlir-mode)))

;; Custom Commands
(defun show-file-name ()
  "Show the full path file name in the minibuffer."
  (interactive)
  (message (buffer-file-name)))

;; Consult
(use-package consult
  :ensure t
  :demand t
  :bind (("C-x m" . consult-kmacro)
         ("M-#" . consult-register-load)
         ("M-'" . consult-register-store)          ;; orig. abbrev-prefix-mark (unrelated)
         ("C-M-#" . consult-register)
         ("M-y" . consult-yank-pop)                ;; orig. yank-pop
         ("M-g g" . consult-goto-line)             ;; orig. goto-line
         ("M-g M-g" . consult-goto-line)           ;; orig. goto-line
         ("M-g o" . consult-outline)               ;; Alternative: consult-org-heading
         ("M-g m" . consult-mark)
         ("M-g k" . consult-global-mark)
         ("M-g i" . consult-imenu)
         ("M-g I" . consult-imenu-multi)
         ("M-s d" . consult-fd)                  ;; Alternative: consult-find
         ("M-s g" . consult-grep)
         ("M-s G" . consult-git-grep)
         ("C-M-s" . consult-ripgrep)
         ("C-s" . consult-line))
  :init)

(use-package embark
  :ensure t
  :bind (("C-j" . embark-act)
         ("C-M-j" . embark-dwim)
         ("C-h B" . embark-bindings)
         :map embark-general-map
         ("Z" . consult-register-store))
  :init
  (setq prefix-help-command #'embark-prefix-help-command))

(use-package embark-consult
  :ensure t
  :after consult
  :after embark)

(use-package marginalia
  :ensure t
  :bind (:map minibuffer-local-map
              ("M-A" . marginalia-cycle))
  :init
  (marginalia-mode))

;; vertico
(use-package vertico
  :ensure t
  :init
  (vertico-mode)
  (setq vertico-cycle t))
(use-package vertico-quick
  :after vertico)

(use-package orderless
  :ensure t
  :custom (completion-styles '(orderless)))

;; Entry keyboard macro
(defun entry-org ()
  "Prints an entry for notes. Includes date generated by shell
command, and a paremeterized color"
  (interactive)
  (insert (format
           "*** %s"
           (shell-command-to-string
            "date -I'seconds' | tr -d '\n' ")
           ))
  )


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Auto Save backup directory
 ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(setq backup-directory-alist
      `(("." . ,(concat user-emacs-directory "backups"))))
(setq auto-save-file-name-transforms
      `((".*" ,(concat user-emacs-directory "backups") t)))


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; ENCODING
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(prefer-coding-system 'utf-8-unix)
(set-default-coding-systems 'utf-8-unix)
(setq-default buffer-file-coding-system 'utf-8-unix)
;; Treat clipboard input as UTF-8 string first; compund text next, etc.
(setq x-select-request-type '(UTF8_STRING COMPOUND_TEXT TEXT STRING))

;; GDB mode
(add-to-list 'auto-mode-alist '("\\.gdb\\'" . gdb-script-mode))
(setq gdb-many-windows t)
(setq gdb-default-window-configuration-file "gdb_window_config")

;; Org mode
(defun my-org-config ()
  (local-set-key (kbd "C-c s") 'org-insert-structure-template)
)
(add-hook 'org-mode-hook 'my-org-config)
(add-hook 'org-mode-hook 'org-modern-mode)

(normal-erase-is-backspace-mode 0)


;; C mode
(setq-default c-basic-offset 2
              tab-width 2
              indent-tabs-mode nil)
(defun pretty-c ()
  (c-set-offset 'arglist-intro '+)
  (c-set-offset 'arglist-cont '0)
  (c-set-offset 'case-label '+)
  (c-set-offset 'inamespace '0)
   )
(add-hook 'c-mode-hook 'pretty-c)
(add-hook 'c++-mode-hook 'pretty-c)

(defconst my-cc-style
  '("cc-mode"
    (c-offsets-alist . ((innamespace . [0])))))

(c-add-style "my-cc-mode" my-cc-style)

(add-to-list 'auto-mode-alist '("\\.tpp\\'" . c++-mode))

;; Hideshow (hs-) Mode
(defun toggle-fold ()
  (interactive)
  (save-excursion
    (end-of-line)
    (hs-toggle-hiding)))
(defun hs-config ()
  (local-set-key (kbd "C-c @ t") 'toggle-fold)
  (local-set-key (kbd "C-c @ s") 'hs-show-block)
  (local-set-key (kbd "C-c 1") 'hs-show-block)
  (local-set-key (kbd "C-c @ h") 'hs-hide-block)
  (local-set-key (kbd "C-c 2") 'hs-hide-block)
  )
(add-hook 'hs-minor-mode-hook 'hs-config)
(add-hook 'prog-mode-hook #'hs-minor-mode)

;; Define function to go to other window backwards
(defun myprevious-window ()
    (interactive)
    (other-window -1))

;; END

